<a href="https://colab.research.google.com/github/yura123123/Deep_Learning/blob/main/Yurii_Chornii_%D0%9A%D0%9D_409_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

Тензор представляє (можливо багатовимірний) масив числових значень. З однією віссю тензор називається вектором . З двома осями тензор називається матрицею . З k>2  осей, ми відкидаємо спеціалізовані назви й просто посилаємось на об’єкт як a  kth  тензор порядку .

PyTorch надає різноманітні функції для створення нових тензорів, попередньо заповнених значеннями. Наприклад, викликавши arange(n), ми можемо створити вектор рівномірно розташованих значень, починаючи з 0 (включено) і закінчуючи n(не включено). За замовчуванням розмір інтервалу дорівнює  1 . Якщо не вказано інше, нові тензори зберігаються в основній пам’яті та призначені для обчислень на основі ЦП.

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Ми можемо отримати доступ до форми тензора (довжини вздовж кожної осі), перевіривши його shapeвластивість.

In [3]:
x.shape

torch.Size([12])

Якщо ми просто хочемо знати загальну кількість елементів у тензорі, тобто добуток усіх елементів фігури, ми можемо перевірити його розмір. Оскільки тут ми маємо справу з вектором, його одиничний елемент shapeідентичний його розміру.

In [4]:
x.numel()

12

Щоб змінити форму тензора, не змінюючи ні кількості елементів, ні їх значень, ми можемо викликати reshapeфункцію. Наприклад, ми можемо перетворити наш тензор, x, з вектора-рядка з формою (12,) в матрицю з формою (3, 4). Цей новий тензор містить точно такі ж значення, але розглядає їх як матрицю, організовану у вигляді 3 рядків і 4 стовпців. Повторюю, хоча форма змінилася, елементи ні. Зверніть увагу, що розмір не змінюється шляхом зміни форми.

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Як правило, ми хочемо, щоб наші матриці були ініціалізовані нулями, одиницями, деякими іншими константами або числами, випадковим чином відібраними з конкретного розподілу. Ми можемо створити тензор, що представляє тензор з усіма елементами, встановленими на 0 і формою (2, 3, 4) наступним чином:

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Аналогічно, ми можемо створити тензори з кожним елементом, встановленим на 1, наступним чином:



In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Часто ми хочемо випадковим чином вибрати значення для кожного елемента в тензорі з деякого розподілу ймовірностей. Наприклад, коли ми створюємо масиви, щоб служити параметрами в нейронній мережі, ми зазвичай ініціалізуємо їх значення випадковим чином. Наступний фрагмент створює тензор із формою (3, 4). Кожен з його елементів випадковим чином відбирається зі стандартного гауссового (нормального) розподілу із середнім значенням 0 і стандартним відхиленням 1.

In [8]:
torch.randn(3, 4)

tensor([[-0.2949,  0.3719, -0.1487, -0.8726],
        [-0.5196,  0.1256,  1.9088, -1.0010],
        [-0.1920, -1.2726,  0.5842,  1.2233]])

Ми також можемо вказати точні значення для кожного елемента в потрібному тензорі, надавши список Python (або список списків), що містить числові значення. Тут крайній список відповідає осі 0, а внутрішній список — осі 1.



In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

Загальні стандартні арифметичні оператори ( +, -, *, /, і **) були зняті до поелементних операцій.



In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Багато інших операцій можна застосовувати поелементно, включаючи унарні оператори, такі як підведення до степеня.



In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

Ми також можемо об’єднати кілька тензорів разом, складаючи їх кінець в кінець, щоб утворити більший тензор. Нам просто потрібно надати список тензорів і вказати системі, вздовж якої осі потрібно об’єднатися. Наведений нижче приклад показує, що відбувається, коли ми об’єднуємо дві матриці вздовж рядків (вісь 0, перший елемент фігури) і стовпців (вісь 1, другий елемент фігури). Ми бачимо, що довжина осі 0 першого вихідного тензора ( 6 ) є сумою довжин осі 0 двох вхідних тензорів ( 3+3 ); тоді як довжина осі другого вихідного тензора-1 ( 8 ) є сумою довжин осі-1 двох вхідних тензорів ( 4+4 ).

MXNET

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Іноді ми хочемо побудувати двійковий тензор за допомогою логічних операторів . Візьмемо як приклад. Для кожної позиції, якщо і рівні в цій позиції, відповідний запис у новому тензорі приймає значення 1, що означає, що логічний твердження є істинним у цій позиції; інакше ця позиція приймає 0.X == YXYX == Y

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Підсумовуючи всі елементи тензора, виходить тензор лише з одним елементом.



In [14]:
X.sum()

tensor(66.)

У більшості випадків ми транслюємо по осі, де масив спочатку має лише довжину 1, як-от у наступному прикладі:



In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

Оскільки aі bє 3×1  і  1×2 відповідно, їх форми не збігаються, якщо ми хочемо їх додати. Ми транслюємо записи обох матриць у більшу 3×2  матриця так: для матриці aвона реплікує стовпці, а для матриці bреплікує рядки перед поелементним додаванням обох.

In [16]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Таким чином, [-1]вибирає останній елемент і [1:3]вибирає другий і третій елементи наступним чином:



In [17]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

Крім читання, ми також можемо записувати елементи матриці, вказуючи індекси.



In [18]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

Якщо ми хочемо призначити кільком елементам однакове значення, ми просто індексуємо всі з них, а потім призначаємо їм значення. Наприклад, звертається до першого та другого рядків, де бере всі елементи вздовж осі 1 (стовпця). Хоча ми обговорювали індексацію для матриць, це, очевидно, також працює для векторів і тензорів більше ніж 2 вимірів.[0:2, :]:



In [19]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

Виконання операцій може призвести до виділення нової пам’яті для результатів хоста. Наприклад, якщо ми напишемо , ми розіменуємо тензор, який раніше вказував на щойно виділену пам’ять, а замість цього вказував на неї. У наступному прикладі ми демонструємо це за допомогою функції Python , яка дає нам точну адресу об’єкта, на який посилається, у пам’яті. Після запуску ми виявимо, що це вказує на інше місце. Це тому, що Python спочатку оцінює , виділяючи нову пам’ять для результату, а потім вказує на це нове місце в пам’яті.Y = X + YYYid()Y = Y + Xid(Y)Y + XY



In [20]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Це може бути небажаним з двох причин. По-перше, ми не хочемо весь час бігати, виділяючи без потреби пам’ять. У машинному навчанні ми можемо мати сотні мегабайт параметрів і оновлювати всі їх кілька разів на секунду. Як правило, ми хочемо виконувати ці оновлення на місці . По-друге, ми можемо вказати на ті самі параметри з кількох змінних. Якщо ми не оновлюємо на місці, інші посилання все одно вказуватимуть на старе розташування пам’яті, що дозволить частинам нашого коду ненавмисно посилатися на застарілі параметри.



На щастя, виконувати операції на місці легко. Ми можемо призначити результат операції раніше виділеному масиву за допомогою позначення зрізу, наприклад, . Щоб проілюструвати цю концепцію, ми спочатку створюємо нову матрицю з такою ж формою, що й інша , використовуючи для виділення блокуY[:] = <expression>ZYzeros_like 0  записи.

In [21]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140082508742192
id(Z): 140082508742192


Якщо значення Xне використовується повторно в наступних обчисленнях, ми також можемо використовувати або зменшити накладні витрати на пам’ять операції.X[:] = X + YX += Y



In [22]:
before = id(X)
X += Y
id(X) == before

True

Перетворення в тензор NumPy ( ndarray) або навпаки легко. Тензор факела і масив numpy будуть ділитися своїми основними місцями пам’яті, і зміна одного за допомогою операції на місці також змінить інше.



In [23]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

Щоб перетворити тензор розміру 1 у скаляр Python, ми можемо викликати itemфункцію або вбудовані функції Python.



In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)